### ISSUE TITLE
Audit occupation - class mappings

### ISSUE THREAD

**Issue by elenapalesis** [mpancia/san-francisco-ethics-d5#6]
https://docs.google.com/spreadsheets/d/19HjzMr6--3ADgf4LkrVGreJcwoYNkqPaPurDzdLKb10/edit#gid=96911554

**Comment by elenapalesis** [comment]
@mpancia I added a column `elena_changed` (to be removed) to the sheet, with value `TRUE` to denote that I changed the original assignment. Let me know when it's reviewed and I'll make a PR to add the changed CSV.

**Comment by mpancia** [comment]
Checked and merged
